export const GET_INFO_REQUEST = "GET_INFO_REQUEST";
export const GET_INFO_SUCCESS = "GET_INFO_SUCCESS";
export const GET_INFO_FAILURE = "GET_INFO_FAILURE";
export const GET_UPCOMING_DATA = 'GET_UPCOMING_DATA';
export const GET_UPCOMING_REQUEST = 'GET_UPCOMING_REQUEST';
export const SET_VALUE = 'SET_VALUE';
export const GET_CONTACT_REQUEST = 'GET_CONTACT_REQUEST';
export const GET_CONTACT_DATA = 'GET_CONTACT_DATA';
export const GET_CALL_STATUS = 'GET_CALL_STATUS';
export const CHANGE_IND = 'CHANGE_IND';
export const CREATE_COMMUNICATION = 'CREATE_COMMUNICATION';
export const GET_COM_ID = 'GET_COM_ID';
export const UPDATE_COMMUNICATION = 'UPDATE_COMMUNICATION';
export const UNIQUE_ID = 'UNIQUE_ID';
export const GET_CALL_DURATION= 'GET_CALL_DURATION';
export const SHOW_FREEDA = "SHOW_FREEDA";


